version: 2.1

jobs:
  prepare:
    docker:
      - image: circleci/node:12.10.0
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install

  eslint:
    docker:
      - image: circleci/node:12.10.0
    steps:
      - run:
          name: ESLint
          command: npm run eslint

  stylelint:
    docker:
      - image: circleci/node:12.10.0
    steps:
      - run:
          name: Prettier
          command: npm run prettier

workflows:
  version: 2
  validate:
    jobs:
      - prepare
      - eslint:
          requires:
            - prepare
      - stylelint:
          requires:
            - prepare